### ISSUE TITLE
Use of Object.assign()

### ISSUE THREAD

**Issue by ix-certification** [indexexchange/gum-gum-adapter#5]
Our wrapper supports Internet Explorer, however, Object.assign() is not supported in Internet Explorer. We need you to make it compatible with ES5. 
https://github.com/indexexchange/gum-gum-adapter/blob/master-v2/gum-gum-htb.js#L230
https://github.com/indexexchange/gum-gum-adapter/blob/master-v2/gum-gum-htb.js#L360
https://github.com/indexexchange/gum-gum-adapter/blob/master-v2/gum-gum-htb.js#L388

**Comment by mxcoder** [comment]
Hi @ix-certification , this has been added to our priorities, we'll get to it asap.

**Comment by mxcoder** [comment]
Hi @ix-certification , we have changes to development-v2 branch for your consideration.
